main: io.github.ascpialgroup.clp.ClutchesPracticePlugin
name: ClutchesPractice
version: 1.0.0
description: This plugin adds a system to learn to clutch.
load: POSTWORLD
author: ASCPIAL Group
website: ascpialgroup.github.io

commands:
   summonhelper:
      description: This command summon the helper armor stand for practice.
      usage: /<command>
      permission: clp.summonhelper
      permission-message: Sorry, you need permission <permission> to do this.


permissions:
    clp.*:
        description: Gives access to all clutches practice commands
        children:
            clp.summonhelper: true
            clp.removehelper: true
            clp.breakblocks: true
    clp.summonhelper:
        description: Allows you to summon an helper armor stand
        default: op
    clp.removehelper:
        description: Allows you to remove an helper armor stand
        default: op
    clp.breakblocks:
        description: Allows you to break blocks in ClutchesPractice active worlds.
        default: op
